package com.mycompany.ej803g;

import java.awt.*;

public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redButton = new javax.swing.JButton();
        actualColorLabel = new javax.swing.JLabel();
        actualColor = new javax.swing.JLabel();
        greenButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        redButtonCounter = new javax.swing.JLabel();
        greenButtonCounter = new javax.swing.JLabel();
        blueButtonCounter = new javax.swing.JLabel();
        yellowButtonCounter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        redButton.setText("Red");
        redButton.addActionListener(this::redButtonActionPerformed);

        actualColorLabel.setBackground(new java.awt.Color(240, 240, 240));
        actualColorLabel.setText("Actual color:");
        actualColorLabel.setOpaque(true);

        actualColor.setBackground(new java.awt.Color(240, 240, 240));
        actualColor.setText(" Default ");
        actualColor.setOpaque(true);

        greenButton.setText("Green");
        greenButton.addActionListener(this::greenButtonActionPerformed);

        blueButton.setText("Blue");
        blueButton.addActionListener(this::blueButtonActionPerformed);

        yellowButton.setText("Yellow");
        yellowButton.addActionListener(this::yellowButtonActionPerformed);

        redButtonCounter.setText("0");

        greenButtonCounter.setText("0");

        blueButtonCounter.setText("0");

        yellowButtonCounter.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(redButton)
                        .addGap(18, 18, 18)
                        .addComponent(redButtonCounter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actualColorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualColor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(greenButton)
                        .addGap(18, 18, 18)
                        .addComponent(greenButtonCounter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blueButton)
                        .addGap(18, 18, 18)
                        .addComponent(blueButtonCounter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yellowButton)
                        .addGap(18, 18, 18)
                        .addComponent(yellowButtonCounter)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redButton)
                    .addComponent(redButtonCounter))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenButton)
                    .addComponent(greenButtonCounter))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueButton)
                    .addComponent(blueButtonCounter))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yellowButton)
                    .addComponent(yellowButtonCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualColorLabel)
                    .addComponent(actualColor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int redCounter=0;
    int greenCounter=0;
    int blueCounter=0;
    int yellowCounter=0;
    
    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        
        actualColor.setText("Red");
        actualColor.setBackground(Color.red);
        
        Container fondo = this.getContentPane();
        fondo.setBackground(Color.red);
        
        redButtonCounter.setText("" + ++redCounter);
        
    }//GEN-LAST:event_redButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        
        actualColor.setText("Green");
        actualColor.setBackground(Color.green);
        
        Container fondo = this.getContentPane();
        fondo.setBackground(Color.green);
        
        greenButtonCounter.setText("" + ++greenCounter);
        
    }//GEN-LAST:event_greenButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        
        actualColor.setText("Blue");
        actualColor.setBackground(Color.blue);
        
        Container fondo = this.getContentPane();
        fondo.setBackground(Color.blue);
        
        blueButtonCounter.setText("" + ++blueCounter);
        
    }//GEN-LAST:event_blueButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        
        actualColor.setText("Yellow");
        actualColor.setBackground(Color.yellow);
        
        Container fondo = this.getContentPane();
        fondo.setBackground(Color.yellow);
        
        yellowButtonCounter.setText("" + ++yellowCounter);
        
    }//GEN-LAST:event_yellowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualColor;
    private javax.swing.JLabel actualColorLabel;
    private javax.swing.JButton blueButton;
    private javax.swing.JLabel blueButtonCounter;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel greenButtonCounter;
    private javax.swing.JButton redButton;
    private javax.swing.JLabel redButtonCounter;
    private javax.swing.JButton yellowButton;
    private javax.swing.JLabel yellowButtonCounter;
    // End of variables declaration//GEN-END:variables
}
